### ISSUE TITLE
Gulp server terminates at demo create with viewer role

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#112]
server.js expects a location header which is not returned if user is not allowed to create a demo:

```
created demo at: undefined

/Users/gjosten/Projects/github-grtjn/demo-cat/server.js:149
      res.write(JSON.stringify({uri: response.headers.location.replace(/(.*\?u
                                                               ^
TypeError: Cannot call method 'replace' of undefined
    at ClientRequest.<anonymous> (/Users/gjosten/Projects/github-grtjn/demo-cat/server.js:149:64)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

server.js needs to be more robust..

**Comment by grtjn** [comment]
Fixed in develop branch.
